disappearing pages
MaymoonaAlBoloshi/stepper-form pull request #12
Opened 2024-10-20 05:29 UTC by ireemalqarni

After implementing React Router for navigation between Page 1 (Personal Info) and Page 2 (Plan Selection), a new issue has arisen where both pages have disappeared, leaving only the sidebar visible. This problem prevents the form from displaying the actual content of the pages, making the multi-step form non-functional.

2024-10-20 09:09 UTC, ireemalqarni commented
This pull request implements navigation from Page 1 to Page 2 and enhances the user interface according to the specified design requirements. The changes include the addition of a toggle component for selecting a plan, proper title and description display, and an updated stepper to indicate the user's current step.

- Added functionality to navigate to Page 2 when the user clicks the "Next" button on Page 1.
- Created a separate toggle component that allows the user to select a single item (plan) as per the design specifications.
- Included "Next" and "Back" buttons on Page 2.
- Configured the "Back" button to navigate the user back to Page 1 when clicked.
- Modified the stepper component to dynamically update as the user navigates between steps.


- Proof of success
- 

https://github.com/user-attachments/assets/0cdb7714-feda-47fc-ab2b-e538db348313

2024-10-20 09:18 UTC, MaymoonaAlBoloshi commented
![image](https://github.com/user-attachments/assets/63dc85e9-6a1d-4be8-9e67-df8d3a52c075)
update the style of the second page cards to match the design

2024-10-20 09:25 UTC, MaymoonaAlBoloshi requested changes

2024-10-20 09:25 UTC, MaymoonaAlBoloshi commented on src/components/FormStepper.tsx
> -
Extract the Step component with props of 
- is active
- title
- sub text
that way we will not be repeating ourselves so many times

2024-10-20 09:25 UTC, MaymoonaAlBoloshi commented on src/pages/page2.tsx
> +    }
I like that you put some effort into commenting 👍🏻  but comment only the parts that are complex, accessive commenting is going to be distracting
always try to make sure that the code is self documenting

2024-10-21 07:20 UTC, MaymoonaAlBoloshi requested changes

2024-10-21 07:20 UTC, MaymoonaAlBoloshi commented on src/components/FormStepper.tsx
> +    </div>
creating an array of objects will be way better, give it the name and URL, then comparing if it's active will be done in a single place

2024-10-21 07:20 UTC, MaymoonaAlBoloshi commented on src/App.tsx
> +    </Routes>
I think you forgot to include the index route, this way it might not load the first page if you start the app

2024-10-21 07:20 UTC, MaymoonaAlBoloshi commented on src/pages/page2.tsx
> +      window.location.href = '/nextpage'; // Change to your actual next page URL
you need to use useNavigation from react router dom here to navigate instead of windows.location

2024-10-21 07:20 UTC, MaymoonaAlBoloshi commented on src/pages/page2.tsx
> +        </div>
lots of repeated code, what about creating a component here and call it OptionCard

2024-10-21 08:20 UTC, MaymoonaAlBoloshi approved these changes
looking good to me, just a small suggestion

2024-10-21 08:20 UTC, MaymoonaAlBoloshi commented on src/pages/page2.tsx
> +            price="$15/mo"
great implementation so far, you ca use an array of objects to make it even simpler something like 
[
{plan: 'Pro', price: '$15/mo"},
...
] the loop over it to create the Option cards dynamically

2024-10-21 08:53 UTC, merged